#!/usr/bin/env bash

repo_path=$HOME/.ha100

check_variable() {
  if test ! $(which vim); then
    echo "Error: vim not found! Please install it first."
    exit 1
  fi

  if [ -e $repo_path ]; then
    echo "Error: $repo_path has already exist! Please remove it before install."
    exit 1
  fi
}

download_repo() {
  git clone --recursive -j4 https://github.com/ha100/dotfiles.git $repo_path
  cd $repo_path
  git submodule update --init --recursive
  if [ ! "$?" -eq '0' ]; then
    echo "Error: clone repository failed!"
    exit 1
  fi
}

download_fonts() {
  git clone https://github.com/powerline/fonts.git
  cd fonts
  ./install.sh

  cd ..
  rm -rf fonts
}

link_files() {
  ln -sf $HOME/.ha100/vimrc.symlink $HOME/.vimrc
  ln -sf $HOME/.ha100/vim.symlink $HOME/.vim
  ln -sf $HOME/.ha100/tmux.symlink $HOME/.tmux.conf
}

check_variable
download_repo
download_fonts
link_files
$repo_path/install.sh

echo "Install finished!"

exit 0
