#!/usr/bin/env bash

repo_path=$HOME/.ha100

checkVariable() {
  if test ! $(which vim); then
    echo "Error: vim not found! Please install it first."
    exit 1
  fi

  if [ -e $repo_path ]; then
    echo "Error: $repo_path has already exist! Please remove it before install."
    exit 1
  fi
}

downloadRepo() {
  git clone --recursive -j4 https://github.com/ha100/dotfiles.git $repo_path
  cd $repo_path
  if [ ! "$?" -eq '0' ]; then
    echo "Error: clone repository failed!"
    exit 1
  fi
}

compileVim() {
  cd ~/.ha100/vim.symlink/bundle/vim

  ./configure --prefix="/usr/local" \
    --enable-gui=no \
    --enable-largefile \
    --with-tlib=ncurses \
    --with-features=huge \
    --disable-netbeans \
    --without-x \
    --disable-nls \
    --enable-multibyte \
    --enable-cscope \
    --enable-luainterp \
    --enable-rubyinterp \
    --enable-perlinterp \
    --enable-tclinterp \
    --enable-pythoninterp \
    --enable-python3interp \
    --with-compiledby="ha100 <hastik@antik.sk>"

  make -j4

  sudo make install
}

installVoltron() {
  cd ~/.ha100/vim.symlink/bundle/voltron
  ./install.sh
}

downloadFonts() {
  git clone https://github.com/powerline/fonts.git
  cd fonts
  ./install.sh

  cd ..
  rm -rf fonts
}

linkFiles() {
  ln -sf $HOME/.ha100/vimrc.symlink $HOME/.vimrc
  ln -sf $HOME/.ha100/vim.symlink $HOME/.vim
  ln -sf $HOME/.ha100/tmux.symlink $HOME/.tmux.conf
  ln -sf $HOME/.ha100/ctags.symlink $HOME/.ctags
  ln -sf $HOME/.ha100/lldbinit-lldb.symlink $HOME/.lldbinit-lldb
  ln -sf $HOME/.ha100/swimma.sh /usr/local/bin/swimma
  chmod +x $HOME/.ha100/swimma.sh
}

checkVariable
downloadRepo
downloadFonts
linkFiles
installVoltron
$repo_path/install.sh
compileVim

echo "Install finished!"

exit 0
